/**
 * Excel export localization (English / Arabic).
 * Translates human-readable report text only — not IDs, emails, GPS, etc.
 */

export const EXPORT_LANG = Object.freeze({
  EN: 'en',
  AR: 'ar',
});

export function normalizeExportLanguage(raw) {
  const v = String(raw || '')
    .trim()
    .toLowerCase();
  if (v === 'ar' || v === 'arabic' || v === 'العربية') {
    return EXPORT_LANG.AR;
  }
  return EXPORT_LANG.EN;
}

const EN = {
  sheetSummary: 'Summary',
  sheetSessionsIndex: 'Sessions Index',
  sheetAdditionalSessions: 'Additional Sessions',
  sheetSession: (n) => `Session ${n}`,
  reportTitle: 'Infinity FSM — Overtime Executive Report',
  companyFallback: 'Enterprise Field Service Management',
  sectionReportMetadata: 'Report Metadata',
  sectionKpis: 'Overall Report KPIs',
  sectionEmployeeBreakdown: 'Employee Summary',
  sectionEmployeeInfo: 'Employee Information',
  sectionOvertimeInfo: 'Overtime Information',
  sectionJourneyTimeline: 'Journey Timeline',
  companyName: 'Company Name',
  generatedBy: 'Generated By',
  generatedAt: 'Generated At',
  applicationVersion: 'Application Version',
  exportType: 'Export Type',
  dateRange: 'Date Range',
  startDate: 'Start Date',
  endDate: 'End Date',
  appliedFilters: 'Applied Filters',
  sessionsInExport: 'Sessions in Export',
  reportLanguage: 'Report Language',
  none: 'None',
  all: 'All',
  exportModeSummary: 'Summary',
  exportModeDetailed: 'Detailed Report',
  languageEnglish: 'English',
  languageArabic: 'العربية',
  kpiTotalTechnicians: 'Total Technicians',
  kpiTotalOvertimeHours: 'Total Overtime Hours',
  kpiTotalSessions: 'Total Sessions / Trips',
  kpiTravelTrips: 'Total Travel Trips',
  kpiNormalSessions: 'Total Normal OT Sessions',
  kpiOvernightTrips: 'Total Overnight Trips',
  kpiApprovedSessions: 'Total Approved Sessions',
  empName: 'Technician Name',
  empEmail: 'Technician Email',
  empApprovedHours: 'Total Approved Hours',
  empWorkedHours: 'Total Worked Hours',
  empSessions: 'Total Sessions / Trips',
  empNormal: 'Normal Overtime Sessions',
  empTravel: 'Travel Overtime Sessions',
  empOvernight: 'Overnight Trips',
  empApproved: 'Approved Sessions',
  empPending: 'Pending Review Sessions',
  empRejected: 'Rejected Sessions',
  sessionId: 'Session ID',
  employeeName: 'Employee Name',
  email: 'Email',
  employeeId: 'Employee ID',
  jobTitle: 'Job Title',
  date: 'Date',
  startTime: 'Start Time',
  endTime: 'End Time',
  createdAt: 'Created At',
  status: 'Status',
  type: 'Type',
  overnight: 'Overnight',
  workedHours: 'Worked Hours',
  calculatedHours: 'Calculated Hours',
  approvedHours: 'Approved Hours',
  workingHours: 'Working Hours',
  travelHours: 'Travel Hours',
  totalDuration: 'Total Duration',
  worksheet: 'Worksheet',
  reviewNotes: 'Review Notes',
  rejectionReason: 'Rejection Reason',
  approvedReviewedBy: 'Approved / Reviewed By',
  approvedReviewedAt: 'Approved / Reviewed At',
  syncStatus: 'Sync Status',
  syncActive: 'Active Session',
  syncSynced: 'Synced',
  openSheet: (name) => `Open ${name}`,
  seeAdditional: 'See Additional Sessions',
  backToIndex: '← Back to Sessions Index',
  noSessions: 'No overtime sessions matched the selected filters.',
  overflowNote: (count, max) =>
    `Note: ${count} additional session(s) appear in “Additional Sessions” (export exceeded ${max} detailed sheets for performance).`,
  sessionReportTitle: (n) => `Overtime Session Report — ${n}`,
  sessionIdLine: (id) => `Session ID: ${id}`,
  yes: 'Yes',
  no: 'No',
  dash: '—',
  photos: 'Photos',
  photosCount: (n) => `Photos (${n})`,
  photoN: (n) => `Photo ${n}`,
  openImage: 'Open image',
  timestamp: 'Timestamp',
  gpsAccuracy: 'GPS Accuracy (m)',
  fullAddress: 'Full Address',
  latitude: 'Latitude',
  longitude: 'Longitude',
  googleMaps: 'Google Maps',
  openMaps: '📍 Open in Google Maps',
  batteryLevel: 'Battery Level',
  networkType: 'Network Type',
  deviceId: 'Device ID',
  devicePlatform: 'Device Platform',
  deviceModel: 'Device Model',
  appVersion: 'App Version',
  stageNotes: 'Stage Notes',
  voiceRecording: 'Voice Recording',
  photoCount: 'Photo Count',
  footerLeft: 'Infinity FSM — Automatically Generated Report',
  footerPage: 'Page &P of &N',
  openOriginalImage: 'Open original image',
  openPhoto: (n) => `Open Photo ${n}`,
  statusApproved: 'Approved',
  statusPendingReview: 'Pending Review',
  statusRejected: 'Rejected',
  statusRunning: 'Running',
  statusCancelled: 'Cancelled',
  statusPendingSync: 'Pending Sync',
  typeNormal: 'Normal',
  typeTravel: 'Travel',
  stageStart: '🟢  START',
  stageArrived: '🔵  ARRIVED',
  stageFinished: '🟣  FINISHED WORK',
  stageEnd: '🔴  END',
  voiceStart: 'Start Voice',
  voiceArrived: 'Arrived Voice',
  voiceFinished: 'Finished Voice',
  voiceEnd: 'End Voice',
  minuteOne: '1 minute',
  minutes: (n) => `${n} minutes`,
  hourOne: '1 hour',
  hours: (n) => `${n} hours`,
  hoursAndMinutes: (h, hLabel, m, mLabel) => `${hLabel} ${mLabel}`,
};

const AR = {
  sheetSummary: 'الملخص',
  sheetSessionsIndex: 'فهرس الجلسات',
  sheetAdditionalSessions: 'جلسات إضافية',
  sheetSession: (n) => `جلسة ${n}`,
  reportTitle: 'إنفنتي FSM — تقرير العمل الإضافي التنفيذي',
  companyFallback: 'إدارة خدمات الميدان المؤسسية',
  sectionReportMetadata: 'بيانات التقرير',
  sectionKpis: 'مؤشرات الأداء الإجمالية',
  sectionEmployeeBreakdown: 'ملخص الموظفين',
  sectionEmployeeInfo: 'معلومات الموظف',
  sectionOvertimeInfo: 'معلومات العمل الإضافي',
  sectionJourneyTimeline: 'الجدول الزمني للرحلة',
  companyName: 'اسم الشركة',
  generatedBy: 'أنشئ بواسطة',
  generatedAt: 'تاريخ الإنشاء',
  applicationVersion: 'إصدار التطبيق',
  exportType: 'نوع التصدير',
  dateRange: 'نطاق التاريخ',
  startDate: 'تاريخ البدء',
  endDate: 'تاريخ الانتهاء',
  appliedFilters: 'المرشحات المطبقة',
  sessionsInExport: 'الجلسات في التصدير',
  reportLanguage: 'لغة التقرير',
  none: 'لا يوجد',
  all: 'الكل',
  exportModeSummary: 'ملخص',
  exportModeDetailed: 'تقرير تفصيلي',
  languageEnglish: 'English',
  languageArabic: 'العربية',
  kpiTotalTechnicians: 'إجمالي الفنيين',
  kpiTotalOvertimeHours: 'إجمالي ساعات العمل الإضافي',
  kpiTotalSessions: 'إجمالي الجلسات / الرحلات',
  kpiTravelTrips: 'إجمالي رحلات السفر',
  kpiNormalSessions: 'إجمالي جلسات العمل الإضافي العادي',
  kpiOvernightTrips: 'إجمالي رحلات المبيت',
  kpiApprovedSessions: 'إجمالي الجلسات المعتمدة',
  empName: 'اسم الفني',
  empEmail: 'بريد الفني',
  empApprovedHours: 'إجمالي الساعات المعتمدة',
  empWorkedHours: 'إجمالي الساعات المحسوبة',
  empSessions: 'إجمالي الجلسات / الرحلات',
  empNormal: 'جلسات العمل الإضافي العادي',
  empTravel: 'جلسات عمل السفر الإضافي',
  empOvernight: 'رحلات المبيت',
  empApproved: 'الجلسات المعتمدة',
  empPending: 'جلسات قيد المراجعة',
  empRejected: 'الجلسات المرفوضة',
  sessionId: 'معرّف الجلسة',
  employeeName: 'اسم الموظف',
  email: 'البريد الإلكتروني',
  employeeId: 'الرقم الوظيفي',
  jobTitle: 'المسمى الوظيفي',
  date: 'التاريخ',
  startTime: 'وقت البدء',
  endTime: 'وقت الانتهاء',
  createdAt: 'وقت الإنشاء',
  status: 'الحالة',
  type: 'النوع',
  overnight: 'المبيت',
  workedHours: 'الساعات المحسوبة',
  calculatedHours: 'الساعات المؤهلة',
  approvedHours: 'الساعات المعتمدة',
  workingHours: 'ساعات العمل',
  travelHours: 'ساعات السفر',
  totalDuration: 'المدة الإجمالية',
  worksheet: 'ورقة العمل',
  reviewNotes: 'ملاحظات المراجعة',
  rejectionReason: 'سبب الرفض',
  approvedReviewedBy: 'اعتمد / راجع بواسطة',
  approvedReviewedAt: 'تاريخ الاعتماد / المراجعة',
  syncStatus: 'حالة المزامنة',
  syncActive: 'جلسة نشطة',
  syncSynced: 'مزامن',
  openSheet: (name) => `فتح ${name}`,
  seeAdditional: 'عرض الجلسات الإضافية',
  backToIndex: '← العودة إلى فهرس الجلسات',
  noSessions: 'لا توجد جلسات عمل إضافي مطابقة للمرشحات المحددة.',
  overflowNote: (count, max) =>
    `ملاحظة: تظهر ${count} جلسة إضافية في «جلسات إضافية» (تجاوز التصدير ${max} ورقة تفصيلية لأسباب الأداء).`,
  sessionReportTitle: (n) => `تقرير جلسة العمل الإضافي — ${n}`,
  sessionIdLine: (id) => `معرّف الجلسة: ${id}`,
  yes: 'نعم',
  no: 'لا',
  dash: '—',
  photos: 'الصور',
  photosCount: (n) => `الصور (${n})`,
  photoN: (n) => `صورة ${n}`,
  openImage: 'فتح الصورة',
  timestamp: 'الوقت',
  gpsAccuracy: 'دقة GPS (م)',
  fullAddress: 'العنوان الكامل',
  latitude: 'خط العرض',
  longitude: 'خط الطول',
  googleMaps: 'خرائط Google',
  openMaps: '📍 فتح في خرائط Google',
  batteryLevel: 'مستوى البطارية',
  networkType: 'نوع الشبكة',
  deviceId: 'معرّف الجهاز',
  devicePlatform: 'منصة الجهاز',
  deviceModel: 'طراز الجهاز',
  appVersion: 'إصدار التطبيق',
  stageNotes: 'ملاحظات المرحلة',
  voiceRecording: 'التسجيل الصوتي',
  photoCount: 'عدد الصور',
  footerLeft: 'إنفنتي FSM — تقرير مُنشأ تلقائيًا',
  footerPage: 'الصفحة &P من &N',
  openOriginalImage: 'فتح الصورة الأصلية',
  openPhoto: (n) => `فتح الصورة ${n}`,
  statusApproved: 'معتمد',
  statusPendingReview: 'قيد المراجعة',
  statusRejected: 'مرفوض',
  statusRunning: 'قيد التشغيل',
  statusCancelled: 'ملغى',
  statusPendingSync: 'بانتظار المزامنة',
  typeNormal: 'عادي',
  typeTravel: 'سفر',
  stageStart: '🟢  البداية',
  stageArrived: '🔵  الوصول',
  stageFinished: '🟣  إنهاء العمل',
  stageEnd: '🔴  النهاية',
  voiceStart: 'صوت البداية',
  voiceArrived: 'صوت الوصول',
  voiceFinished: 'صوت إنهاء العمل',
  voiceEnd: 'صوت النهاية',
  minuteOne: '1 دقيقة',
  minutes: (n) => `${n} دقيقة`,
  hourOne: 'ساعة واحدة',
  hours: (n) => `${n} ساعة`,
  hoursAndMinutes: (h, hLabel, m, mLabel) =>
    h === 1 ? `ساعة واحدة و ${mLabel}` : `${h} ساعة و ${mLabel}`,
};

export function excelStrings(lang) {
  return normalizeExportLanguage(lang) === EXPORT_LANG.AR ? AR : EN;
}

/** Human-readable duration for Excel text cells (never decimal hours). */
export function formatDurationProseFromMinutes(minutes, lang = EXPORT_LANG.EN) {
  const t = excelStrings(lang);
  if (minutes === null || minutes === undefined || minutes === '') {
    return t.dash;
  }
  const n = Number(minutes);
  if (!Number.isFinite(n)) return t.dash;
  const safe = Math.max(0, Math.round(n));
  const h = Math.floor(safe / 60);
  const m = safe % 60;
  if (h === 0) {
    return m === 1 ? t.minuteOne : t.minutes(m);
  }
  const hLabel = h === 1 ? t.hourOne : t.hours(h);
  if (m === 0) {
    return hLabel;
  }
  const mLabel = m === 1 ? t.minuteOne : t.minutes(m);
  return t.hoursAndMinutes(h, hLabel, m, mLabel);
}

export function formatDurationProseFromHours(hours, lang = EXPORT_LANG.EN) {
  const t = excelStrings(lang);
  if (hours === null || hours === undefined || hours === '') return t.dash;
  if (hours === t.dash || hours === '—') return t.dash;
  const n = Number(hours);
  if (!Number.isFinite(n)) return t.dash;
  return formatDurationProseFromMinutes(Math.round(n * 60), lang);
}

export function statusLabel(status, lang = EXPORT_LANG.EN) {
  const t = excelStrings(lang);
  switch (String(status || '').toUpperCase()) {
    case 'APPROVED':
      return t.statusApproved;
    case 'PENDING_REVIEW':
      return t.statusPendingReview;
    case 'REJECTED':
      return t.statusRejected;
    case 'RUNNING':
      return t.statusRunning;
    case 'CANCELLED':
      return t.statusCancelled;
    case 'PENDING_SYNC':
      return t.statusPendingSync;
    default:
      return status || t.dash;
  }
}

export function typeLabel(type, lang = EXPORT_LANG.EN) {
  const t = excelStrings(lang);
  switch (String(type || '').toUpperCase()) {
    case 'NORMAL':
      return t.typeNormal;
    case 'TRAVEL':
      return t.typeTravel;
    default:
      return type || t.dash;
  }
}

/** Overnight applies to Travel overtime only. */
export function overnightLabel(record, lang = EXPORT_LANG.EN) {
  const t = excelStrings(lang);
  if (String(record?.type || '').toUpperCase() !== 'TRAVEL') return t.dash;
  return record.isOvernight ? t.yes : t.no;
}

export function stageMetaForLang(lang = EXPORT_LANG.EN) {
  const t = excelStrings(lang);
  return [
    {
      key: 'startJourney',
      title: t.stageStart,
      voiceLabel: t.voiceStart,
      headerArgb: 'FF16A34A',
      bodyArgb: 'FFF0FDF4',
      legacyPhoto: 'startPhoto',
      legacyGps: 'startGps',
      legacyAt: 'startAt',
      legacyAddress: 'startAddress',
      legacyDevice: 'startDeviceId',
    },
    {
      key: 'arrivedAtWorkSite',
      title: t.stageArrived,
      voiceLabel: t.voiceArrived,
      headerArgb: 'FF2563EB',
      bodyArgb: 'FFEFF6FF',
    },
    {
      key: 'finishedWork',
      title: t.stageFinished,
      voiceLabel: t.voiceFinished,
      headerArgb: 'FF7C3AED',
      bodyArgb: 'FFF5F3FF',
    },
    {
      key: 'endJourney',
      title: t.stageEnd,
      voiceLabel: t.voiceEnd,
      headerArgb: 'FFDC2626',
      bodyArgb: 'FFFEF2F2',
      legacyPhoto: 'endPhoto',
      legacyGps: 'endGps',
      legacyAt: 'endAt',
      legacyAddress: 'endAddress',
      legacyDevice: 'endDeviceId',
    },
  ];
}
